
--DEMOMEMBER 테이블 생성 쿼리
CREATE TABLE DEMOMEMBER(
   ID VARCHAR2(50) NOT NULL,
   PW VARCHAR2(300) NOT NULL,
   NAME VARCHAR2(100) NOT NULL,
   EMAIL VARCHAR2(100) NOT NULL,
   PHONE VARCHAR2(50) NOT NULL,
   AUTH VARCHAR2(20) NOT NULL,
   DELFLAG CHAR(1) NOT NULL,
   REGDATE DATE NOT NULL,
   CONSTRAINT "DEMOMEMBER_PK" PRIMARY KEY(ID)
)
--DEMOBOARD 테이블 생성 쿼리
CREATE TABLE DEMOBOARD(
	SEQ NUMBER,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000),
	STEP NUMBER NOT NULL,
	DEPTH NUMBER NOT NULL,
	REFER NUMBER NOT NULL,
	READCOUNT NUMBER,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT "DEMOBOARD_PK" PRIMARY KEY(SEQ),
	CONSTRAINT "DEMOBOARD_FK" FOREIGN KEY("ID") REFERENCES DEMOMEMBER("ID") 
)

--SEQ 1씩 증가
CREATE SEQUENCE DEMOBOARD_SEQ START WITH 1 INCREMENT BY 1;

--회원생성(ROLE_USER) 암호화 전 더미테이블
INSERT INTO GD.DEMOMEMBER
(ID, PW, NAME, EMAIL, PHONE, AUTH, DELFLAG, REGDATE)
VALUES('DEMO01', '1234', 'DEMO01', 'DEMO01@GMAIL.COM', '010-1234-5678', 'ROLE_USER', 'N', SYSDATE);

INSERT INTO GD.DEMOMEMBER
(ID, PW, NAME, EMAIL, PHONE, AUTH, DELFLAG, REGDATE)
VALUES('DEMO02', '1234', 'DEMO02', 'DEMO02@GMAIL.COM', '010-1234-5678', 'ROLE_USER', 'N', SYSDATE);

INSERT INTO GD.DEMOMEMBER
(ID, PW, NAME, EMAIL, PHONE, AUTH, DELFLAG, REGDATE)
VALUES('DEMO03', '1234', 'DEMO03', 'DEMO03@GMAIL.COM', '010-1234-5678', 'ROLE_USER', 'N', SYSDATE);

INSERT INTO GD.DEMOMEMBER
(ID, PW, NAME, EMAIL, PHONE, AUTH, DELFLAG, REGDATE)
VALUES('DEMO04', '1234', 'DEMO04', 'DEMO04@GMAIL.COM', '010-1234-5678', 'ROLE_USER', 'N', SYSDATE);

INSERT INTO GD.DEMOMEMBER
(ID, PW, NAME, EMAIL, PHONE, AUTH, DELFLAG, REGDATE)
VALUES('DEMO05', '1234', 'DEMO05', 'DEMO05@GMAIL.COM', '010-1234-5678', 'ROLE_USER', 'N', SYSDATE);


--회원생성(ROLE_ADMIN) 더미테이블

INSERT INTO GD.DEMOMEMBER
(ID, PW, NAME, EMAIL, PHONE, AUTH, DELFLAG, REGDATE)
VALUES('admin', '1234', 'ADMIN', 'ADMIN@GMAIL.COM', '010-1234-5678', 'ROLE_ADMIN', 'N', SYSDATE);



--DEMOMEMBER_STATEMENT QUERY----
--(1) 회원전체조회(등록일순 내림차순)
SELECT ID,NAME,EMAIL,PHONE, AUTH, DELFLAG, REGDATE
FROM DEMOMEMBER 
ORDER BY REGDATE DESC;

--(2) 회원가입
INSERT INTO GD.DEMOMEMBER
(ID, PW, NAME, EMAIL, PHONE, AUTH, DELFLAG, REGDATE)
VALUES('DEMO01', '1234', 'DEMO01', 'DEMO01@GMAIL.COM', '010-1234-5678', 'ROLE_USER', 'N', SYSDATE);

--(3) 로그인
SELECT ID,NAME,EMAIL,PHONE ,AUTH,REGDATE 
	FROM DEMOMEMBER d 
		WHERE ID='DEMO01' AND PW='1234' AND DELFLAG ='N';

---------------------------------------


